<?php

/**
 * @file
 * This function includes implementation of hooks related to user interface
 * of ajax-ified chat functionality.
 */


/**
 * Implements hook_menu().
 *
 * This implementation registers two different pages:
 * - Single form add / edit form.
 * - Administration panel for ajax chat.
 */
function ajax_chat_ui_menu() {
  // This is the minimum information you can provide for a menu item.
  $items['ajax_chat_ui/chat_entry_form'] = array(
    'title' => 'Chat entry form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_chat_ui_chat_entry_form'),
    'access arguments' => array('add chat entry'),
    'file' => 'ajax_chat_ui.pages.inc',
  );
  // This is a menu item for a form.
  $items['ajax_chat_ui/admin'] = array(
    'title' => 'Ajax chat administration panel',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_chat_ui_admin_form'),
    'access arguments' => array('administer chat'),
    'file' => 'ajax_chat_ui.pages.inc',
  );

  return $items;
}


/**
 * Implementation of ajax callback for chat entry form.
 *
 * According to documentation
 * http://api.drupal.org/api/drupal/includes!ajax.inc/group/ajax/7,
 * such function can create one of few possible values:
 * - String value (just to render as plain HTML)
 * - Render API array
 * - Or (and this is current case) array with list of
 * ajax commands. You can see ajax commands documentation here:
 * http://api.drupal.org/api/drupal/includes!ajax.inc/group/ajax_commands/7
 *
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 */
function ajax_chat_ajax_update_callback($form, $form_state) {
  $commands = array();

  // Save message submitted by form. We use public API from ajax_chat module.
  ajax_chat_entries_save(array($form_state['values']));

  // This command will call jQuery.html() method on chat list wrapper.
  // This div will be propagated with rendered list of chat entries.
  $commands[] = ajax_command_html(
    '.ajax-chat-wrapper',
    theme('chat_entries_list')
  );

  // Return array structure. This array will say ajax framework, that
  // this output is list of commands.
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );

}
